# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Eaton, FYI
author: Jeff Eaton
email: "jeff@eaton.fyi"
summary: A spicy mix of content architecture, omnichannel CMS strategy, and digital team facilitation.
url: "https://eaton.fyi"
analytics: "UA-168755040-1"
twitter_username: eaton
github_username:  eaton


# Build settings
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  - speaking
  - writing
  - projects
    

# A list of the pages to display in the navigation bar
header_pages:
  - about.md
  - writing.md
  - speaking.md
  - contact.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
